// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetriggerMail.Data;

#nullable disable

namespace RetriggerMail.Migrations
{
    [DbContext(typeof(InsuranceDbContext))]
    [Migration("20260616123343_initialadd")]
    partial class initialadd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RetriggerMail.Models.CommunicationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("MessageBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientMobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CommunicationLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimNumber = "CLM123",
                            IsSuccess = false,
                            MessageBody = "Your claim CLM123 is under review.",
                            RecipientEmail = "customer1@test.com",
                            RecipientMobile = "9876543210",
                            SentDate = new DateTime(2026, 6, 15, 18, 3, 43, 263, DateTimeKind.Local).AddTicks(3932),
                            TemplateName = "Claim Update Email"
                        },
                        new
                        {
                            Id = 2,
                            ClaimNumber = "CLM123",
                            IsSuccess = true,
                            MessageBody = "Claim CLM123 status updated.",
                            RecipientEmail = "customer1@test.com",
                            RecipientMobile = "9876543210",
                            SentDate = new DateTime(2026, 6, 15, 18, 3, 43, 263, DateTimeKind.Local).AddTicks(3952),
                            TemplateName = "Claim Update SMS"
                        },
                        new
                        {
                            Id = 3,
                            ClaimNumber = "CLM456",
                            IsSuccess = true,
                            MessageBody = "Your claim CLM456 has been approved.",
                            RecipientEmail = "customer2@test.com",
                            RecipientMobile = "9123456789",
                            SentDate = new DateTime(2026, 6, 14, 18, 3, 43, 263, DateTimeKind.Local).AddTicks(3954),
                            TemplateName = "Claim Approved Email"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
